name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/publish.yml'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed for changed-files action

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          scope: '@senthanal'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm test

      # Get changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43

      - uses: JS-DevTools/npm-publish@v3
        if: contains(steps.changed-files.outputs.all_changed_files, 'src/scan-cli/') || contains(steps.changed-files.outputs.all_changed_files, 'src/scan-lib/')
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: 'dist/@senthanal/deep-scan-cli'

      - uses: JS-DevTools/npm-publish@v3
        if: contains(steps.changed-files.outputs.all_changed_files, 'src/scan-cli/') || contains(steps.changed-files.outputs.all_changed_files, 'src/scan-lib/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
          package: 'dist/@senthanal/deep-scan-cli'
